In [2]:
import pandas as pd
import statsmodels.api as sm

In [25]:
df_adv=pd.read_csv('Datasets/Advertising.csv')
df_adv=df_adv.drop(['Unnamed: 0'],axis=1)
print(df_adv.columns)

Index(['TV', 'radio', 'newspaper', 'sales'], dtype='object')

In [28]:
#x=df_adv.iloc[:,:-1]
x=df_adv[['TV','radio','newspaper']]
y=df_adv['sales']
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ...
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64

In [32]:
## Fit a OLS model with intercept on Tv and Radio
x=sm.add_constant(x)
model=sm.OLS(y,x).fit()

model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Tue, 11 Aug 2020   Prob (F-statistic):           1.58e-96
Time:                        15:58:17   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.9389      0.312      9.422      0.000       2.324       3.554
TV             0.0458      0.001     32.809      0.000       0.043       0.049
radio          0.1885      0.009     21.893      0.000       0.172       0.206
newspaper     -0.0010      0.006     -0.177      0.860      -0.013       0.011
==============================================================================
Omnibus:                       60.414   Durbin-Watson:                   2.084
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              151.241
Skew:                          -1.327   Prob(JB):                     1.44e-33
Kurtosis:                       6.332   Cond. No.                         454.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [35]:
x[['TV','radio','newspaper']].corr()
#There is no correlation among the features..So there is no Multicollineartiy here.

                 TV     radio  newspaper
TV         1.000000  0.054809   0.056648
radio      0.054809  1.000000   0.354104
newspaper  0.056648  0.354104   1.000000

In [36]:
#Salary Data
df_sal=pd.read_csv('Datasets/salary_data.csv')
df_sal

,Department,Rank_Code,Gender,Salary_9_mo,Avg_Cont_Grants,logSalary,LogACG,Engineering
0,CCE E,2,M,87380.00000,16666.666670,11.378022,9.721166,1
1,AN S,2,M,59797.63577,415871.333300,10.998721,12.938131,0
2,FSHNF,2,F,64786.00000,427231.333300,11.078845,12.965081,0
3,COM S,2,M,94050.00000,340321.000000,11.451582,12.737645,0
4,BBMBA,2,F,62744.00000,79949.000000,11.046818,11.289144,0
...,...,...,...,...,...,...,...,...
350,A B E,1,M,89699.00000,212888.000000,11.404215,12.268521,1
351,PL P,2,M,54796.90854,271143.333300,10.911389,12.510403,0
352,STAT,2,M,68186.00000,50000.000000,11.129995,10.819778,0
353,CHEM,1,M,170590.90740,298857.000000,12.047024,12.607720,0
354,AN S,2,M,60908.72666,666.666667,11.017132,6.502290,0